# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/bookings
spring.datasource.username=postgres
spring.datasource.password=postgres

# Enable statistics for debugging
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Disable during production!
spring.jpa.properties.hibernate.hbm2ddl.auto=update